version: '3'

volumes:
  dverein_local_postgres_data: {}
  dverein_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dverein_local_django
    container_name: dverein_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dverein_production_postgres
    container_name: dverein_local_postgres
    volumes:
      - dverein_local_postgres_data:/var/lib/postgresql/data
      - dverein_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: dverein_local_docs
    container_name: dverein_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./dverein:/app/dverein:z
    ports:
      - "9000:9000"
    command: /start-docs

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: dverein_local_node
    container_name: dverein_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
